---
Name: multidomain
After:
  - '#requestprocessors'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        MultiDomainMiddleware: '%$SilverStripe\Control\Middleware\MultiDomainMiddleware'

#SilverStripe\MultiDomain\MultiDomain:
#  allow_subdomains: false