---
Name: multidomain
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        MultiDomainMiddleware: '%$SilverStripe\MultiDomain\MultiDomainRequestFilter'

SilverStripe\MultiDomain\MultiDomain:
  allow_subdomains: false
